### ISSUE TITLE
Protocol Secure Flow Tests failures

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#370]
Tests were ignored in the commit
https://github.com/alex-dukhno/database/pull/369/commits/73f20fbb4b95186f6566db71c929e60eebf39169

backtrace:
```
failures:
758

759
---- tests::accept_client_request::sending_accept_notification_for_ssl_only_secure stdout ----
760
thread 'tests::accept_client_request::sending_accept_notification_for_ssl_only_secure' panicked at 'assertion failed: `(left == right)`
761
  left: `[]`,
762
 right: `[83]`', src\protocol\src\tests\accept_client_request.rs:128:9
763
stack backtrace:
764
   0: backtrace::backtrace::trace_unsynchronized
765
             at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
766
   1: std::sys_common::backtrace::_print_fmt
767
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
768
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
769
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
770
   3: core::fmt::write
771
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
772
   4: std::io::Write::write_fmt<test::helpers::sink::Sink>
773
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\io\mod.rs:1537
774
   5: std::io::impls::{{impl}}::write_fmt<Write>
775
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\impls.rs:176
776
   6: std::sys_common::backtrace::_print
777
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
778
   7: std::sys_common::backtrace::print
779
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
780
   8: std::panicking::default_hook::{{closure}}
781
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
782
   9: std::panicking::default_hook
783
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:214
784
  10: std::panicking::rust_panic_with_hook
785
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
786
  11: std::panicking::begin_panic_handler
787
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:437
788
  12: std::panicking::begin_panic_fmt
789
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:391
790
  13: protocol::tests::accept_client_request::sending_accept_notification_for_ssl_only_secure::{{closure}}
791
             at .\src\tests\accept_client_request.rs:128
792
  14: core::future::from_generator::{{impl}}::poll<generator-0>
793
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\future\mod.rs:78
794
  15: futures_lite::future::block_on::{{closure}}<tuple<>,core::future::from_generator::GenFuture<generator-0>>
795
             at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.11.0\src\future.rs:89
796
  16: std::thread::local::LocalKey<core::cell::RefCell<tuple<parking::Parker, core::task::wake::Waker>>>::try_with<core::cell::RefCell<tuple<parking::Parker, core::task::wake::Waker>>,closure-0,tuple<>>
797
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\thread\local.rs:263
798
  17: std::thread::local::LocalKey<core::cell::RefCell<tuple<parking::Parker, core::task::wake::Waker>>>::with<core::cell::RefCell<tuple<parking::Parker, core::task::wake::Waker>>,closure-0,tuple<>>
799
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\thread\local.rs:239
800
  18: futures_lite::future::block_on<tuple<>,core::future::from_generator::GenFuture<generator-0>>
851
  11: std::panicking::begin_panic_handler
852
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:437
853
  12: std::panicking::begin_panic_fmt
854
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:391
855
  13: protocol::tests::accept_client_request::sending_reject_notification_for_none_secure::{{closure}}
856
             at .\src\tests\accept_client_request.rs:103
857
  14: core::future::from_generator::{{impl}}::poll<generator-0>
858
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\future\mod.rs:78
859
  15: futures_lite::future::block_on::{{closure}}<tuple<>,core::future::from_generator::GenFuture<generator-0>>
860
             at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.11.0\src\future.rs:89
861
  16: std::thread::local::LocalKey<core::cell::RefCell<tuple<parking::Parker, core::task::wake::Waker>>>::try_with<core::cell::RefCell<tuple<parking::Parker, core::task::wake::Waker>>,closure-0,tuple<>>
862
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\thread\local.rs:263
863
  17: std::thread::local::LocalKey<core::cell::RefCell<tuple<parking::Parker, core::task::wake::Waker>>>::with<core::cell::RefCell<tuple<parking::Parker, core::task::wake::Waker>>,closure-0,tuple<>>
864
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\thread\local.rs:239
865
  18: futures_lite::future::block_on<tuple<>,core::future::from_generator::GenFuture<generator-0>>
866
             at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.11.0\src\future.rs:79
867
  19: protocol::tests::accept_client_request::sending_reject_notification_for_none_secure
868
             at .\src\tests\accept_client_request.rs:84
869
  20: protocol::tests::accept_client_request::sending_reject_notification_for_none_secure::{{closure}}
870
             at .\src\tests\accept_client_request.rs:83
871
  21: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
872
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\ops\function.rs:233
873
  22: alloc::boxed::{{impl}}::call_once
874
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\liballoc\boxed.rs:1081
875
  23: std::panic::{{impl}}::call_once
876
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\panic.rs:318
877
  24: std::panicking::try::do_call
878
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\panicking.rs:348
879
  25: std::panicking::try
880
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\panicking.rs:325
881
  26: std::panic::catch_unwind
882
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libstd\panic.rs:394
883
  27: test::run_test_in_process
884
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libtest\lib.rs:541
885
  28: test::run_test::run_test_inner::{{closure}}
886
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libtest\lib.rs:450
887
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by silathdiir** [comment]
I found the same issue yesterday in PR #368 . It seems that it is related with `Cargo.lock` update when running `cargo update` for all packages. So I only updated `native-tls` in PR #368 .
